import os
from fpdf import FPDF
from datetime import datetime
from models.db import fs, reports_col, records_col
from bson.objectid import ObjectId
from utils.recommendations import get_recommendations

def generate_pdf_report(pred_id, user_id, username):
    history = records_col.find_one({'_id': ObjectId(pred_id), 'user_id': user_id})
    if not history:
        return None, "Not found"

    existing = reports_col.find_one({'prediction_id': pred_id})
    if existing and existing.get('pdf_grid_id'):
        pdf_file = fs.get(existing['pdf_grid_id'])
        pdf_bytes = pdf_file.read()
        
        pdf_path = os.path.join('static', 'reports', f"report_{pred_id}.pdf")
        os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
        with open(pdf_path, 'wb') as f:
            f.write(pdf_bytes)
            
        return pdf_path, history

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 15, txt="Hypertension Predictive Report", ln=1, align="C")
    pdf.set_font("Arial", size=10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, txt="Generated by Pulse Predictive System", ln=1, align="C")
    pdf.ln(10)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt="Patient Information", ln=1)
    pdf.set_draw_color(100, 100, 241)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", size=12)
    pdf.cell(95, 10, txt=f"Date: {history['date'].strftime('%Y-%m-%d %H:%M')}", ln=0)
    pdf.cell(95, 10, txt=f"Patient: {username}", ln=1)
    pdf.cell(95, 10, txt=f"Gender: {history.get('Gender', '')}", ln=0)
    pdf.cell(95, 10, txt=f"Age Group: {history.get('Age', '')}", ln=1)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt="Clinical Data", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", size=12)
    pdf.cell(95, 10, txt=f"Systolic BP: {history.get('Systolic', '')}", ln=0)
    pdf.cell(95, 10, txt=f"Diastolic BP: {history.get('Diastolic', '')}", ln=1)
    pdf.cell(95, 10, txt=f"Severity: {history.get('Severity', '')}", ln=0)
    pdf.cell(95, 10, txt=f"Family History: {history.get('History', '')}", ln=1)
    pdf.cell(95, 10, txt=f"Medication: {history.get('TakeMedication', '')}", ln=0)
    pdf.cell(95, 10, txt=f"Controlled Diet: {history.get('ControlledDiet', '')}", ln=1)
    pdf.cell(95, 10, txt=f"Breath Shortness: {history.get('BreathShortness', '')}", ln=0)
    pdf.cell(95, 10, txt=f"Visual Changes: {history.get('VisualChanges', '')}", ln=1)
    pdf.cell(95, 10, txt=f"Nose Bleeding: {history.get('NoseBleeding', '')}", ln=0)
    pdf.cell(95, 10, txt=f"When Diagnosed: {history.get('WhenDiagnosed', '')}", ln=1)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt="Prediction Result", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 12, txt=f"Stage: {history.get('risk_label', '')} ({history.get('confidence', '')}% confidence)", ln=1)
    pdf.ln(5)

    shap_summary = history.get('shap_summary', '')
    if shap_summary:
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, txt="AI Explanation (SHAP)", ln=1)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(0, 8, txt=shap_summary)
        pdf.ln(5)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt="Health Recommendations", ln=1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", size=11)
    
    dynamic_recs = get_recommendations(history)
    for adv in dynamic_recs:
        pdf.multi_cell(0, 8, txt=adv)

    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    pdf_grid_id = fs.put(pdf_bytes, filename=f"report_{pred_id}.pdf", content_type='application/pdf')
    reports_col.insert_one({'prediction_id': pred_id, 'user_id': user_id, 'pdf_grid_id': pdf_grid_id, 'generated_at': datetime.utcnow()})

    pdf_path = os.path.join('static', 'reports', f"report_{pred_id}.pdf")
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
    with open(pdf_path, 'wb') as f:
        f.write(pdf_bytes)

    return pdf_path, history
